name: deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Deploy'
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY}}
        command: |
          cd @shiorilabs/services/shiori
          docker-compose down
          docker-compose pull
          docker-compose up -d


